#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate_schemas --shared
python manage.py migrate_schemas
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
