volumes:
  neuralterrena_local_postgres_data: {}
  neuralterrena_local_postgres_data_backups: {}
  neuralterrena_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: neuralterrena_local_django
    container_name: neuralterrena_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: neuralterrena_production_postgres
    container_name: neuralterrena_local_postgres
    volumes:
      - neuralterrena_local_postgres_data:/var/lib/postgresql/18/docker
      - neuralterrena_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '2354:5432'

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: neuralterrena_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: neuralterrena_local_redis
    volumes:
      - neuralterrena_local_redis_data:/data

  celeryworker:
    <<: *django
    image: neuralterrena_local_celeryworker
    container_name: neuralterrena_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: neuralterrena_local_celerybeat
    container_name: neuralterrena_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: neuralterrena_local_flower
    container_name: neuralterrena_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  mjml:
    image: neuralterrena_local_mjmlserver
    container_name: neuralterrena_local_mjmlserver
    build:
      context: .
      dockerfile: ./compose/local/mjml/Dockerfile
    restart: always
    environment:
      HOST: "0.0.0.0"
      PORT: "28101"
      MJML_ARGS: "--mjml.minify=true --mjml.validationLevel=strict"
    ports:
      - "28101:28101"
